# Site settings
name: Go, Xiaoyi
email: yolandawang87@gmail.com
author: Yolanda Wang
url: #''
resume_site: #http://www.hifreud.com/Resume.io/
github: https://github.com/YolandaWang87/
baseurl: "/LessOrMore"
description: Xiaoyi(Yolanda)'s Study Blog
meta_description: Xiaoyi(Yolanda)'s Study Blog
motto: Learn how to better learn
banner: Thinking is fascinating

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: YolandaWang87

# Build settings
markdown: kramdown

#baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

